theme: jekyll-theme-minimal
title: Nail Tosun
description: My office in C-114 in Electrical and Electronics Engineering Departmant in METU. Email:nail.tosun@metu.edu.tr
logo: /images/pp.PNG
mathjax: true
